portal/templates/500.html
Without loading the staticfiles library, `{% static ...%}` causes an exception, masking the real error that triggered the 500 page
=> Fix usage of static tag in 500 template

portal/tests/base_test.py, portal/tests/test_emails.py, portal/views/registration.py
When the captcha view is imported it was using the then-set value of the CAPTCHA_ENABLED flag.
When the selenium tests ran after a normal TestCase it would already have been imported and thus
not be set up to ignore captchas.
=> Fix captcha related test bug

portal/tests/test_security.py, portal/views/teacher/teach.py
Checks that the correct teacher is logged in.
Return the same error code (404) if either the wrong teacher is logged in or if the class the reminder cards are requested for does not exist. This prevents any information being leaked about which classes exist in the database.
=> Add authentication checks to reminder cards page

portal/autoconfig.py
Pen-testing identified that messages to be displayed after login were stored as HTML in a cookie. This change stores the message in the session (ie server-side).
=> Use session storage for messages.

portal/static/portal/js/riveted.min.js, portal/templates/portal/base.html
Add the riveted.js plugin to track active time on pages.
- If the user is clicking scrolling or typing with a page open this is logged as active time. 
- If the tab is not visible or the user closes the tab or they are inactive on the tab for over 30 seconds the timer is paused until the user returns to activity on the page.
=> Added riveted.js plugin to monitor active time on each page

portal/templates/portal/base.html
Placing the analytics code in the head will give more reliable analytics. Leaving it at the end of the body may result it not getting run before the user moves to a different page.
=> Move analytics script into head from bottom of the page

portal/templates/portal/teach/teacher_home.html
Currently there are CFL_Pupil_Certificates.zip (old logo, all certificates are separate files zipped together) and CFL_Pupil_Certificates.pdf (new logo all certificates on one pdf) sitting next to each other in the google cloud platform where all teaching materials are stored. This change will update the reference so the new certificates will be accessed.
=> Change .zip to .pdf for the pupil certificates.

README.md
The idea is to add a "template" like that at the beginning (or elsewhere) of the other open code for life repos here, so we can share the links more confidently at conferences etc, and people understand better the structure of our project on github.
Feel free to comment please!
=> Adding a header blurb for the README - will adapt to other repos

portal/urls.py
The URL redirects to the new teaching packs did not have a name, causing a link on the home page (visible when logged in as a teacher) to break the entire view. They now have a name.
=> Fix crash caused by url redirect.

portal/migrations/0001_squashed_0041_new_news.py
When loading the migration, include timezone data.
=> Remove naive DateTime warnings

portal/static/portal/sass/styles.scss, portal/templates/redesign/base_new.html
In the new styles.scss file, all font sizes for text, buttons, etc... are converted from pxs to rems. Rems are relative to the root HTML font size. Therefore added some media queries in styles.scss file so that every element's font size would be updated responsively.
The different widths used in the media queries follow [Bootstrap's tutorial](http://getbootstrap.com/css/#grid-media-queries).
=> Redesign 7 - Made base HTML font size responsive

.travis.yml, portal/tests/base_test.py, portal/tests/base_test_new.py, portal/tests/custom_handler.py, test_settings.py
Similarly to Rapid Router, makes Travis use Chrome/ChromeDriver for selenium testing instead of Firefox/Webdriver.
With Firefox, all the tests would be run in 14 minutes and 11 seconds.
With Chrome, all the tests now run in 8 minutes and 40 seconds, which is almost twice as quick!
=> Travis with Chromedriver

portal/admin.py
Select widget has been replaced by either a readonly label or a raw_id_field which opens foreign key values in another page.
=> Makes Teacher and Student admin models accessible

portal/emailMessages_new.py, portal/forms/teach.py, portal/forms/teach_new.py, portal/helpers/emails_new.py, portal/static/portal/sass/styles.scss, portal/templates/redesign/teach_new/dashboard.html, portal/templates/redesign/teach_new/onboarding_classes.html, portal/templates/redesign/teach_new/onboarding_print.html, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach/onboarding_classes_page.py, portal/tests/test_class_new.py, portal/tests/test_organisation.py, portal/tests/test_organisation_new.py, portal/tests/test_teacher_new.py, portal/tests/test_teacher_student_new.py, portal/tests/test_views_new.py, portal/tests/utils/email.py, portal/urls.py, portal/views/email_new.py, portal/views/teacher/dashboard.py, portal/views/teacher/teach.py, portal/views/teacher/teach_new.py
The following forms now work on the new teacher dashboard page:
- Edit school details form
- Add a class form
- Edit account details form
Because those 3 forms are now on the same page (whereas before they were each on their own), the edit school details form and add a class form had clashing IDs (ie, the field for entering the school name and the field for entering the class name both had 'id_name' id.)
Therefore the create a class field has been renamed to 'id_class_name' which is why some modifications had to made on the forms.py file and some of the current views files.
Tests have been added for those forms as well.
**This PR doesn't require any others to be merged.**
=> Redesign 15 - Teacher dashboard forms

portal/static/portal/js/teach_class.js, portal/static/portal/sass/styles.scss, portal/templates/redesign/teach_new/class_new.html, portal/tests/pageObjects/portal/teach/class_page_new.py, portal/tests/test_class_new.py, portal/tests/test_teacher_student_new.py, portal/urls.py, portal/views/teacher/teach_new.py
Functionality for deleting students from classes added.
**This PR contains mostly Python changes. The few CSS and HTML changes have been done to fix the CSS issues of the student list table in the edit class page - no new page has been created.**
=> Redesign 25 - Edit class page: delete students

portal/templates/redesign/teach_new/class_new.html, portal/views/teacher/dashboard.py
Following issue #445 and @j4mesholland 's new wireframe:
- the user is redirected to the new class page upon creating a new class from the dashboard
- the introduction text on the page has been shortened
- there is now a button to prompt the user to add new students to the new class
=> Updates for edit class page

portal/tests/utils/classes.py, portal/tests/utils/classes_new.py
I would like to set class name in test to some string containing accent in order to fix ocadotechnology/rapid-router#891
=> Allow changing the class_name in tests when creating a class

portal/templates/redesign/reset_password_email.html, portal/templates/registration/password_reset_email.html
Details of issue: #465 
The message has been rewritten: 'You're' has been replaced with 'You are' so there is no more need for the apostrophe.
=> Updated reset password email with no apostrophe

example_project/example_project/settings.py, portal/templates/redesign/teach_new/dashboard.html, portal/templates/two_factor/core/setup_complete.html, portal/views/teacher/dashboard.py, portal/views/teacher/home_new.py
After login in with 2FA, the teachers are redirected to the new redesigned pages.
Other 2FA functionality (such as managing backup tokens, disabling 2FA...) still uses the old pages but still redirects to the new pages once the task is done.
**Please note that this won't work straight away - after this is merged it will require the merge of the PR on the appengine**
=> Redesign: 2FA login redirect

portal/static/portal/sass/styles.scss, portal/templates/redesign/base_new.html, portal/templates/redesign/teach_new/dashboard.html, portal/templates/redesign/teach_new/viewer_new.html
- The text on anchors now remains the same colour upon hover and click.
- The 'allow' button in the teacher dashboard is in the centre of the table cell.
- The sub nav bar in the PDF viewer page is now vertically centred.
=> HTML/CSS fixes: Anchors

portal/static/portal/sass/styles.scss, portal/templates/redesign/base_new.html
Buttons have a different shade when the user hovers over them, indicating that they are clickable.
=> HTML/CSS fixes: Button shades on hover

portal/static/portal/sass/partials/_banners.scss, portal/templates/portal/teach/viewer.html
- The link to download the video was actually the one to download the PDF, now fixed.
- The banner now uses Flexbox.
=> PDF viewer page: correct video download URL

portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_subnavs.scss
Because of some CSS rules using the 'visited' anchor attribute, the text of the anchor would disappear after the user had clicked on the anchor. Now fixed!
=> Anchors fix: text stays after anchor has been visited

portal/emailMessages.py, portal/forms/teach.py, portal/tests/test_teacher.py, portal/tests/utils/email.py, portal/tests/utils/teacher.py, portal/views/home.py
Users who try to register using an email address already associated with an account will receive the following email:
Code for Life: Duplicate account error
A user is already registered with this email address: <email_address>.
If you've already registered, please login: <login_link>.
Otherwise please register with a different email address.
=> Registration: users get an email if they try to reregister

portal/static/portal/sass/modules/_colours.scss, portal/static/portal/sass/partials/_utils.scss, portal/templates/portal/teach/viewer.html, portal/views/teacher/pdfs.py
- LKS2 assessment guide, self-assessment sheet and teacher record sheet now show the right PDF in the viewer and provide the correct PDF to download.
- LKS2 'extra' resources show the correct title in the PDF viewer.
- Links to any key stage's assessment guide from the self-assessment sheet and the teacher record sheet pages now link to the correct PDFs and do not raise a 404 error.
- Added `-` to some of the PDF viewer pages' titles to stay consistent.
- Reincorporated the CSS for the KS tags which had mysteriously disappeared...
=> Resources page: fixes issues with PDFs 

portal/helpers/captcha.py
Checked on https://stackoverflow.com/questions/35137724/python-requests-client-error-bad-request-but-works-after-website-has-been-open , trying to solve the recaptcha issue
=> Recaptcha fixes

portal/tests/test_class.py, portal/tests/test_teacher.py, portal/views/teacher/dashboard.py
Following issue #598:
- The 'Add class' and 'Edit account details' forms in dashboard work also for non-admin teachers.
- Tests have been added to ensure a similar issue doesn't arise again.
The problem was that the back end was checking whether a teacher is a admin for every form in the dashboard, whereas it actually needs to check that only for the 'Edit school details' form.
=> Teacher dashboard: fixed forms for non-admin teachers

portal/templates/portal/teach/onboarding_print.html
Button now says 'Back to class' instead of 'Finish setup'... and redirects to class rather than finishing the setup.
=> Adding students from dashboard page has correct button in nav bar

portal/templates/portal/about.html
- Number of registered users is now 100,000 and not 95,000.
- Link to contact form links to contact form and not top of help and support page.
=> About page: minor updates

portal/views/home.py
Following issue #600, when the contact is accessed from the footer link or from the header link in the Help and Support page (which adds a `#contact` anchor in the URL) and it is successfully submitted, when the page is reloaded it goes to the top of the page where the success message appears.
=> Contact form: anchor updated to top of page

.coveragerc, .travis.yml, setup.cfg
Following @mikebryant's suggestions, Coveralls should check:
- test files
- ratelimit
- migrations
The only file which should be excluded in the portal folder is _versions.py.
=> Re-sets Coveralls properly

portal/forms/organisation.py, portal/templates/portal/teach/onboarding_school.html, portal/tests/pageObjects/portal/teach/onboarding_organisation_page.py, portal/tests/test_organisation.py
- Error messages have been moved under the fields instead of below.
- The error message for the postcode now reads 'Please enter a valid postcode or ZIP code'.
- Tests!
- Other minor PEP8 fixes.
=> School creation page: clearer postcode error message

portal/forms/play.py, portal/templates/portal/play/student_edit_account.html, portal/templates/portal/play/student_join_organisation.html, portal/tests/pageObjects/portal/login_page.py, portal/tests/pageObjects/portal/play/account_page.py, portal/tests/pageObjects/portal/play/join_school_or_club_page.py, portal/tests/pageObjects/portal/signup_page.py, portal/tests/test_independent_student.py, portal/tests/test_school_student.py, portal/tests/test_teacher.py, portal/tests/utils/messages.py, portal/views/play.py
- Tests now cover when students/indep students edit their details (name, password, etc...), which also includes cases where the form is invalid.
- If a student tries to load these pages without being logged in they will now be redirected appropriately to the login page.
=> Student edit account page: tests and correct redirect

portal/urls.py, reports/urls.py
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/738)
=> Removed use of django.conf.urls.patterns()

portal/helpers/emails.py
RemovedInDjango110Warning: render() must be called with a dict, not a Context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/741)
=> Replaced Context with a dictionary

portal/static/portal/sass/partials/_text.scss
Fixes issue #710 by resizing font correctly, is branched correctly this time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/762)
=> Fixes text resizing, branched correctly

portal/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/775)
=> Django: Support for string view arguments to url() is deprecated and will be removed in Django 1.10

Pipfile.lock, setup.py
`django-two-factor-auth` relies on `django-otp` (required: >=0.3.4,<0.99).
However recently `django-otp` upgraded to `0.5.0` which dropped support for django 1.10 and below, causing our builds to fail. 
Although not ideal, I fixed the `django-otp` version to 0.4.3 to satisfy all the dependency requirements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/800)
=> Fix master travis build by fixing a subdependency to django-otp version to 0.4.3

.scss-lint.yml, portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_header.scss, portal/templates/portal/base.html
Updated logout menu to fit with new design specification.
fixes: https://github.com/ocadotechnology/codeforlife-portal/issues/803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/807)
=> Update profile dropdown

portal/static/portal/sass/partials/_header.scss
Added the fit-content value to the menu's right side's width attribute, that way the Register and Log In buttons never need to wrap on two lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/868)
=> Login buttons wrap properly always

portal/static/portal/sass/partials/_header.scss, portal/templates/portal/base.html
- Increased the width of the menu's right side.
- Because of the width increase, also reduced the width of the dropdown to 75% of parent instead of 90%.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/870)
=> Fixes log in buttons properly

portal/static/portal/js/sticky_subnav.js
It was unnecessary because when the sub-navigation bar sticks to the top of the screen the menu gets overlapped automatically. When it's a warning bar, both the bar and the menu remain at the top of the screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/874)
=> Deleted instruction to hide menu

portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_header.scss
Font size and home icon adjust to screens from 760px to 1200px wide so that the buttons don't overlap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/886)
=> Changes in font and home icon

portal/templates/portal/teach/materials.html
Adds the materials page in a cache block which caches the page for an hour.
Django documentation: https://docs.djangoproject.com/en/2.1/topics/cache/#s-template-fragment-caching
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/896)
=> Caches materials page

portal/static/portal/sass/modules/_levels.scss, portal/static/portal/sass/partials/_images-backgrounds.scss, portal/static/portal/sass/partials/_subnavs.scss, portal/templates/portal/base.html
Changed z-indexes so that the elements are properly placed and the dropdown menu gets closed when the user scrolls so it doesn't become unreachable on Rapid Router's page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/928)
=> fix: z-indexes of top menu, dropdown and subnavs

portal/__init__.py
Because a release had been manually created on this repo (tag 1.1.1), the codebase's version was outdated (1.1.0) and the automatic versioning wouldn't work. Syncing them should resume proper functionality of the automatic versioning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/930)
=> fix(views/__init__.py): increment version manually to sync with project

test_settings.py
So far the static root constant in `test_settings.py` pointed to `portal/static`. This was fine before since this was where the old `styles.css` file was stored, and that was where the project got the final styles from.
Ever since the redesign however, and the use of Sass instead of CSS, the Sass files took over the `portal/static` directory and `styles.css` is now compiled automatically in `example_project/example_project/static`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/929)
=> fix(test_settings.py): Point to example project static root so Selenium tests run using compiled styles

portal/views/api.py
codeforlife-deploy-appengine has specifically said it doesn't want authentication on api for the django-rest-framework. However, we need it to check whether the user is an admin or not for the `/users/inactive` api. This PR enables `SessionAuthentication` just for the InactiveUsers apis
=> fix: Add SessionAuthentication for inactive users api

portal/templates/portal/teach.html
Link now points to the updated PDF and the description includes KS 1, 2 and 3
=> fix: link points to right PDF and wording updated

portal/views/teacher/solutions_level_selector.py
This fixes an issue we found during deployment
=> fix: Remove context_instance leftover from Django 1.10 Upgrade

portal/views/home.py
Should be more efficient than the previous cyclic check through all the student users in the independent student registration form.
=> fix: now using filter when checking for already registered email addresses

portal/templates/portal/partials/aimmo_games_table.html
At some point the button font size on the AI:MMO game table was changed and the table column layout wasn't updated to reflect that for screen sizes of over 1200px of width. The change is now implemented
Screenshot:
=> fix: game table column size

portal/static/portal/sass/partials/_forms.scss
**Issue**
When clicking login there is a quick pink flash at the bottom of the screen. This is connected to the Independent Student Login section that was being hidden in that split second of a frame. Looking closer, there is also another flash that is white.
**Solution**
For the pink flash, I went to the css code for the login of the Independent Student and just hid it so that it doesn't appear when loading in. The white flash is something that I have not found a solution to however. It seems to just be a rendering problem that I do not how to change.
=> fix: Got rid of pink flash 

portal/autoconfig.py, portal/permissions.py, portal/static/portal/js/delete_aimmo_game.js
Having two permission classes checking the same request seemed to somehow alter the data and make the delete request user Anonymous (IsTeacher and IsPreviewUser permissions). It's related to Django's authentication, and it might have been fixed when the session authentication was added to the game view on the AI:MMO project, but having one unified permission to check if a user can delete a game makes the code more compact.
The reason for having two separate permission classes before was the fact that AI:MMO didn't make the distinction between safe methods and unsafe methods, and it could clash with the fact that not all the users who have access to the games are teachers. Since AI:MMO now makes the distinction, this shouldn't be needed anymore.
=> fix: permission error on staging

portal/static/portal/sass/partials/_footer.scss
Made social media icons inline with each other through a few css tweaks. All that was added was the two lines of code: display: flex; align-items: center.
=> fix: Fixed social media spacing

portal/forms/organisation.py, portal/tests/pageObjects/portal/teach/onboarding_organisation_page.py
**Problem**
The "create/join school" required a password for the teacher to input. This is not needed.
**Solution**
We decided to take out the password definition under the OrganisationForm class and the definition for the clean password. This removed the requirement to input your password.
=> fix: removed password requirement for create school

example_project/example_project/settings.py, portal/templatetags/future.py
When upgrading to Django 1.10, an issue arose with the 2FA configuration that went undetected. A stub for the future tag library was created based on the recommendation [here](https://github.com/alsoicode/django-admin-sortable/issues/151#issuecomment-237205015).
=> fix: created stub for future library

portal/static/portal/js/join_create_game_toggle.js
The game creation form had been changed to sanitise input, but the regular expression added didn't allow spaces between alphanumeric characters. This has been fixed now, while special characters are still not allowed.
=> fix: changed regex to allow spaces

portal/templates/portal/base.html, portal/templates/portal/base_old.html, portal/templates/portal/play/student_details.html, portal/templates/portal/play/student_edit_account.html, portal/templates/portal/play/student_join_organisation.html
Add conditions to prevent independent students from having access to the `View Scoreboard` button in the navigation bar. (cf #988)
This PR also removes a link to the scoreboard in the details page "more" links block.
I also noticed that the logout button display was broken on the `Join school` and `Change password` pages. I have included the fix in this MR. Let me know if you prefer a separate PR for this.
=> fix: remove scoreboard button

portal/views/teacher/pdfs.py
This PR replaces KS2 S2 1 resource sheet PDF's URL with the correct one.
=> fix: correct URL for KS2 PDF

portal/templates/portal/base_old.html
This PR adds the AI:MMO header link in the old base, making it visible to users even in the non-redesigned pages (including the 2FA pages).
=> fix: add AI:MMO header button to old base file

portal/views/teacher/pdfs.py
Updated challenge PDFs, uploaded them on the cloud storage, changed the respective urls to link to these.
**Challenge 1:**
**Challenge 2:**
=> fix: updated PDFs links to refer to AIMMO_v2 folder on the cloud

README.md
I was having issues running `pipenv install` related to zlib missing when installing `Pillow 3.3.2`.
I found a fix and included in the readme in the hopes of helping anybody else using mac os mojave.
=> docs: add solution to fix Pillow install issues on macos mojave

portal/templates/portal/base.html
There is a bug whereby the AI:MMO link in `base.html` links to landing page and not the home page for preview users, if the user is currently on the Rapid Router landing page.
However, the fix for this bug was wrong as it replaced the AI:MMO link for non-preview users. This means that currently, if non-preview users click on the AI:MMO link in the nav bar, it tries to take them to the AI:MMO home page. This raises a 401 as they are not authorised to view this page.
This PR fixes this problem by essentially reverting the previous PR on this branch. Another PR will shortly follow to fix the original problem.
=> fix: AI:MMO link replaced with landing page for non preview users

.github/ISSUE_TEMPLATE/new_task.md
Added the "Copywrite Requirements" optional section on GitHub's new task template.
=> docs: add copywrite requirements to new task template

.travis.yml
Currently the tests run on PR builds as well as release builds, after the PRs have been merged.
Since each test stage takes around 12 minutes, this slows down the release process by about 25 minutes (since there are two builds happening after merging).
Sometimes the tests also fail because of Selenium timing out, which just stops the release process until someone notices nothing has been deployed.
This PR should fix this since tests will only run in PR builds!
=> ci: make tests run only in PR builds

portal/templates/portal/terms.html
There was a typo in our Terms of Use (a misspelling of Code for Life). This PR fixes that.
=> fix: typo in our terms of use page

portal/static/portal/sass/partials/_images.scss, portal/templates/portal/partials/benefits.html, portal/templates/portal/play_aimmo.html, portal/templates/portal/play_rapid-router.html, portal/tests/snapshots/snap_test_partials.py
The benefits partial was adjusted for the new Kurono play page but the change didn't propagate to the other two places it's used in (teach page and play RR page). This PR makes the change present in the partial itself so it's applied across pages.
=> fix: benefits partial

example_project/example_project/settings.py, portal/autoconfig.py
X-Type Content Options was being set in the example project's settings - moved it to autoconfig.py
=> fix: changed XTCP header setting to autoconfig

.travis.yml, Pipfile.lock, portal/app_settings.py, portal/forms/admin_login.py, portal/static/portal/sass/old_styles.scss, portal/templates/registration/login.html, portal/tests/pageObjects/portal/admin/admin_login_page.py, portal/tests/pageObjects/portal/base_page.py, portal/tests/test_admin.py, portal/urls.py, portal/views/admin.py, pytest.ini, setup.py
This PR fixes an issue that arose within the admin login view after the Django 1.11 upgrade.
The problem was that the login function in Django's auth.views is now deprecated and replaced with a class called LoginView instead. More details [here](https://docs.djangoproject.com/en/1.11/topics/auth/default/#all-authentication-views).
=> fix: remove deprecated function from admin login view

Pipfile.lock, setup.py
Removed `django-classy-tags` dependency from the `setup.py` file. It's still installed as part of `sekizai`.
=> fix: removed django-classy-tags from setup.py file

portal/templates/portal/base.html, portal/templates/portal/base_old.html, portal/templates/portal/teach/materials.html
Now that the global cache prefix no longer has the version in it, I have made sure the django html templates are still versioned in the cache.
=> fix: cache templates with version

portal/tests/conftest.py, portal/tests/test_aimmo_dashboards.py, portal/tests/test_materials.py, portal/urls.py, portal/views/teacher/__init__.py
This bug fix allows teachers who have saved the previous URL for teaching resources to redirect successfully to the new URL
=> fix: pass in kwargs in materials viewer redirect 

cfl_common/MANIFEST.in
This fixes other packages using common templates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1420)
=> fix: include templates in common manifest

portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_header.scss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1520)
=> fix: mobile navbar buttons max width, padding, Ocado logo, account icon, dropdown

portal/admin.py, portal/views/cron/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2165)
=> fix: Fix verify email link

portal/views/cron/user.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2167)
=> fix: iterate over queryset

cfl_common/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2234)
=> fix: Revert Django 3.2.23 (CI/CD measuring)

cfl_common/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2238)
=> fix: Upgrade Django to 3.2.23 again (CI/CD measuring)

.codecov.yml, .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2244)
=> ci: Replace Razbot with CFLbot

portal/templates/portal/email_verification_needed.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2262)
=> feat: outlook button on verify email

portal/forms/teach.py, portal/templates/portal/teach/teacher_edit_class.html, portal/tests/snapshots/snap_test_partials.py, portal/tests/test_views.py, portal/urls.py, portal/views/student/play.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2338)
=> fix: Updates for Python Den

portal/templates/portal/play.html
This is the Blockly link in the "Starting with Blockly" section on the "Play" page!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2346)
=> fix: update broken blockly documentation link

Pipfile.lock, portal/templates/portal/teach/teacher_edit_class.html, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2388)
=> fix: untick locked worksheet ids

portal/templates/portal/teach.html
Linked new docs to teacher landing page. Couldn't find the relevant gitbook files within the repo so am unable to remove the now redundant pages from my end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2433)
=> fix: Fix for #2432
