ocadotechnology/codeforlife-portal

MANIFEST.in, setup.cfg, setup.py, versioneer.py
This is needed for the new deployment infrastructure
=> Fix the packaging of wheels

portal/views/admin.py
And cleaned some commented code
=> Added Workspaces data to know about uses

portal/static/portal/js/play.js, portal/tests/pageObjects/portal/play_page.py, portal/tests/test_independent_student.py, portal/tests/utils/student.py
=> Fix the independent student login page

portal/tests/test_emails.py, portal/urls.py
Sending an email about the number of new registered users for the past weeks - to be used in a cron job in appengine project
=> adding new users notification

portal/admin.py
=> Adding filters for schools - search by region

portal/templates/portal/teach/teacher_lesson_plans_python.html
Not changed spelling of resource, but spotted that my weird name spelling hadn't made it across. Refused to watch the video in case it's actually me...
=> Change spelling of name

portal/templates/portal/home.html
As suggested in #185, this commit changes the ticker interval to 8s.
=> Increased news ticker interval to 8s - Fixes #185

portal/views/teacher/teach.py
- json had a redundant import
- devices_for_user was not imported but used in teacher_disable_2fa
=> Fix teach.py imports

portal/admin.py
So we can add preverified EVs to users not created via the app, that some people have been using for testing.
=> Added EmailVerification to Django CMS.

portal/helpers/email.py, portal/migrations/0050_refactor_emailverifications_2.py, portal/models.py, portal/views/admin.py, portal/views/email.py
- Delete original models
- Begin renaming new ones
=> Refactor EV to decouple from UserProfile - Stage 2

portal/migrations/0051_add_missing_ev_records.py
This fixes the issue we had where the manually created test users were no longer able to log in due to a lack of EV records.
=> Added migration to ensure that all verified users have a verified EV record.

.travis.yml, portal/models.py, portal/permissions.py, portal/tests/test_security.py, portal/tests/test_views.py, test_settings.py
* Regression test for #213
* Fix tests that weren't running as they weren't signing in successfully.
=> Add test and fix old one

portal/migrations/0052_refactor_emailverifications_3.py, portal/models.py
- Finish renaming new 'user' relation.
=> Refactor EV to decouple from UP - Stage 3

portal/templates/redesign/base_new.html, portal/templates/redesign/base_popup.html, portal/templates/redesign/play_new/base_new.html, portal/templates/redesign/teach_new/base_class_edit.html, portal/templates/redesign/teach_new/base_logged_in.html, portal/templates/redesign/teach_new/base_materials.html, portal/templates/redesign/teach_new/base_new.html, portal/templates/redesign/teach_new/base_registering.html, portal/urls.py
- Created new URLs in urls.py to be able to access new hidden pages.
- Added all necessary base HTML files. These include the menu bar and the footer (plus the previous plugins/components from the current website, ie mouseflow, CMS call, etc...)
- These files are once again a work in progress. They will change as functionality is added, which will change the URLs and make some base files obsolete. These series of pull requests are so that anyone can view the current progress of the redesign :)
=> Redesign 3 - Base files and new URLs

portal/static/portal/sass/styles.scss, portal/templates/redesign/about_new.html, portal/templates/redesign/base_new.html, portal/templates/redesign/help-and-support_new.html, portal/templates/redesign/home_new.html, portal/templates/redesign/login_popup.html, portal/templates/redesign/play_new.html, portal/templates/redesign/register_popup.html, portal/templates/redesign/teach_new.html, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/dashboard.html, portal/templates/redesign/teach_new/materials_new.html, portal/templates/redesign/teach_new/onboarding_classes.html, portal/templates/redesign/teach_new/onboarding_complete.html, portal/templates/redesign/teach_new/onboarding_join_pending.html, portal/templates/redesign/teach_new/onboarding_print.html, portal/templates/redesign/teach_new/onboarding_school.html, portal/templates/redesign/teach_new/onboarding_students.html, portal/templates/redesign/terms_new.html
This adds the following pages to the redesign project:
- Home page
- Teacher landing page / Educate page
- Student landing page / Play page / Rapid Router intro page
- About us page
- Help and support & Contact us pages (which have been merged)
- Terms of use page
- Registration popup
- Login popup
- Onboarding: creating/joining a school page
- Onboarding: joining a school, request pending page
- Onboarding: adding a class page
- Onboarding: adding students page
- Onboarding: print student IDs page
- Onboarding: setup complete page (with links to other sections)
- Teacher resources page
- Teacher dashboard
- Teacher dashboard: edit a class page
All of these are still a work in progress. Functionality needs to be added, some styling still needs some tweaking, some text needs updating, …
=> Redesign 4 - New HTML pages

portal/static/portal/sass/styles.scss, portal/templates/redesign/about_new.html, portal/templates/redesign/base_new.html, portal/templates/redesign/home_new.html, portal/templates/redesign/login_popup.html, portal/templates/redesign/teach_new/dashboard.html, portal/tests/pageObjects/portal/base_page.py, portal/tests/pageObjects/portal/home_page_new.py, portal/tests/pageObjects/portal/login_page.py, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/test_teacher_new.py, portal/urls.py, portal/views/home_new.py
A registered teacher can now enter their login details in the login popup and it redirects them to the dashboard page with their username on the banner.
Please note:
- **This pull request requires all 4 other PRs to be merged in order to be tested.**
- The rest of the login functionality (ie displaying teacher's classes, their students, their school, etc...) will come later in another pull request.
- The error messages on the login form do not show when wrong credentials are entered. This is because the login form is now in a popup (therefore will need further investigation). **This issue will not be once the login is converted from popup to actual page.**
**Tests for the login form have been added.**
=> Redesign 5 - Teacher login form now works

portal/static/portal/sass/styles.scss, portal/templates/redesign/home_new.html
- Homepage banner has been flexed.
- Registration anchors aligned.
- Logo image name fixed.
**This PR doesn't require any other PR to be merged.**
=> First CSS fixes

portal/static/portal/sass/styles.scss, portal/templates/redesign/base_new.html
- In mobile layout, register and login button have been moved into one of the collapsible divs.
- Horizontal logo is consequently taking up more space.
- Collapsible divs have been made smaller to fit phone sizes.
- Tablet to mobile breakpoint has been updated.
=> Redesign 12 - Updated media queries and layouts

portal/static/portal/js/passwordStrength.js, portal/static/portal/js/passwordStrength_new.js, portal/static/portal/sass/styles.scss, portal/templates/portal/play.html, portal/templates/redesign/register.html
Adds functionality to the 'no password' text below the registration form.
Depending on the strength of the password entered, the colour of the strength dot changes and so does the strength text.
**This pull request does not require any other pull requests to be merged.**
=> Redesign 11 - Password strength check on registration form

portal/templates/redesign/teach_new/dashboard.html, portal/urls.py, portal/views/teacher/dashboard.py
- School/admin details & text shows appropriately.
- Most tables are populated (except the external student requests table, which will be added when the functionality for independent students is implemented.)
**This PR doesn't require any other PR to be merged.**
=> Redesign 14 - Teacher dashboard data

portal/tests/base_test.py, portal/tests/base_test_new.py
Reverted 'finally' to 'else' and moved attempts increment outside of try except finally block.
=> Travis: Timeout while loop optimisation

portal/emailMessages_new.py, portal/forms/teach.py, portal/static/portal/sass/styles.scss, portal/templates/portal/teach/teacher_classes.html, portal/templates/redesign/base_new.html, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/dashboard.html, portal/tests/pageObjects/portal/teach/classes_page.py, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach/teach_base_page_new.py, portal/tests/test_organisation_new.py, portal/tests/utils/organisation_new.py, portal/urls.py, portal/views/organisation_new.py, portal/views/teacher/dashboard.py, portal/views/teacher/teach.py, portal/views/teacher/teach_new.py
This PR adds the following functionality to the teacher dashboard:
- An admin teacher can allow another teacher to join the school upon request.
- An admin teacher can deny another teacher's request to join the school.
- An admin teacher can remove/kick a teacher from the school.
- An admin teacher can toggle another teacher's admin status.
- An admin teacher can disable another teacher's 2 factor authentication.
- Any teacher can click on the 'edit class' button in the classes table to view the page specific to the class. **Any further functionality (edit class settings, move/delete/add students, etc...) will be added later.**
=> Redesign 17 - Teacher dashboard buttons

portal/forms/teach_new.py, portal/templates/redesign/login.html, portal/tests/pageObjects/portal/login_page.py, portal/tests/test_school_student_new.py, portal/views/home_new.py, portal/views/teacher/teach_new.py
Students who attend a school or a club can now log in via the login form.
Few things to note about this PR:
- After login, the student is redirected to the current student dashboard, with the old design. This is normal as the student pages are not being redesigned straight away.
- **This PR does not require any other pull request to be merged.**
=> Redesign 18 - Student login form

portal/forms/play_new.py, portal/forms/teach.py, portal/forms/teach_new.py, portal/static/portal/js/passwordStrength_new.js, portal/static/portal/sass/styles.scss, portal/templates/portal/teach.html, portal/templates/redesign/register.html, portal/tests/pageObjects/portal/signup_page.py, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach_page.py, portal/tests/test_independent_student_new.py, portal/tests/test_organisation_new.py, portal/tests/utils/student_new.py, portal/views/email_new.py, portal/views/home.py, portal/views/home_new.py
The independent students' registration form is now functional.
=> Redesign 19 - Independent student register form

portal/forms/play_new.py, portal/static/portal/js/student_login.js, portal/templates/redesign/login.html, portal/tests/pageObjects/portal/login_page.py, portal/tests/test_independent_student_new.py, portal/tests/utils/email.py, portal/tests/utils/student_new.py, portal/views/email_new.py, portal/views/home_new.py
The independent students' login form is now functional.
**Requires 19 to be merged.**
=> Redesign 20 - Independent student login form

portal/views/teacher/pdfs.py
=> Typo fix in PDF

portal/templates/portal/teach/materials/home.html, portal/views/teacher/pdfs.py
Used to show title: 'Levels guide 50-109'. Updated to '51-109'.
=> Levels guide 51-109 shows correct title

portal/tests/test_api.py, portal/urls.py, portal/views/api.py
Needs API protection in deploy project
=> API for aggregated active users data - fixes #393

portal/static/portal/sass/styles.scss, portal/templates/redesign/home_new.html
Following issue #425, the home page banner text has been updated and the 'find out more about us' button has been added.
=> Redesign: Updated home page

.eslintrc, portal/static/portal/js/teach_class.js, portal/templates/redesign/teach_new/base_registering.html, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/onboarding_print.html, portal/tests/pageObjects/portal/teach/class_page_new.py, portal/tests/test_class_new.py, portal/urls.py, portal/views/teacher/teach_new.py
Teachers can now delete empty classes.
**READY TO MERGE \o/**
=> Redesign 22 - Edit class page: delete class

portal/forms/teach_new.py, portal/models.py, portal/static/portal/sass/styles.scss, portal/templates/redesign/base_new.html, portal/templates/redesign/email_verification_failed_new.html, portal/templates/redesign/email_verification_needed_new.html, portal/templates/redesign/home_new.html, portal/templates/redesign/play_new.html, portal/templates/redesign/teach_new.html, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/dashboard.html, portal/templates/redesign/teach_new/materials_new.html, portal/templates/redesign/teach_new/onboarding_complete.html, portal/templates/redesign/teach_new/onboarding_print.html, portal/templates/redesign/teach_new/teacher_edit_class_new.html, portal/templates/redesign/teach_new/teacher_move_class_new.html, portal/templates/redesign/teach_new/viewer_new.html, portal/templates/redesign/terms_new.html, portal/tests/pageObjects/portal/teach/class_page_new.py, portal/tests/pageObjects/portal/teach/class_settings_page_new.py, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach/move_class_page_new.py, portal/tests/test_class_new.py, portal/tests/utils/classes_new.py, portal/urls.py, portal/views/teacher/dashboard.py, portal/views/teacher/teach.py, portal/views/teacher/teach_new.py
Teachers can now edit class settings and transfer classes to other teachers.
=> Redesign 23 - Edit class page: edit class settings and transfer class

portal/app_settings.py, portal/helpers/emails.py, portal/helpers/emails_new.py, portal/views/email.py, portal/views/email_new.py
Needs https://github.com/ocadotechnology/codeforlife-deploy-appengine/pull/40 to be merged
=> salesforce integration

portal/forms/teach_new.py, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/teacher_edit_student_new.html, portal/templates/redesign/teach_new/teacher_student_reset_new.html, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach/edit_student_page.py, portal/tests/pageObjects/portal/teach/edit_student_password_page.py, portal/tests/test_teacher_student_new.py, portal/tests/utils/organisation_new.py, portal/urls.py, portal/views/teacher/teach_new.py
Teachers can now edit students' names and passwords.
=> Redesign 24 - Edit class page: edit student details

portal/static/portal/js/teach_class_new.js, portal/static/portal/sass/styles.scss, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/onboarding_print.html, portal/tests/pageObjects/portal/teach/class_page_new.py, portal/tests/test_teacher_student_new.py, portal/urls.py, portal/views/teacher/teach_new.py
Functionality for reset students' passwords in class page added.
=> Redesign 26 - Edit class page: reset student passwords

portal/tests/pageObjects/portal/game_page.py
to complement https://github.com/ocadotechnology/rapid-router/pull/907
=> last cow back to pasture

portal/forms/teach_new.py, portal/models.py, portal/static/portal/js/teach_class_new.js, portal/static/portal/sass/styles.scss, portal/templates/redesign/base_new.html, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/teacher_move_students_new.html, portal/templates/redesign/teach_new/teacher_move_students_to_class_new.html, portal/templatetags/app_tags.py, portal/tests/pageObjects/portal/teach/class_page_new.py, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach/move_students_disambiguate_page_new.py, portal/tests/pageObjects/portal/teach/move_students_page_new.py, portal/tests/test_teacher_student_new.py, portal/urls.py, portal/views/email_new.py, portal/views/home_new.py, portal/views/organisation_new.py, portal/views/teacher/dashboard.py, portal/views/teacher/teach_new.py
Functionality for moving students from class to class added.
=> Redesign 27 - Edit class page: move students

portal/forms/teach_new.py, portal/static/portal/js/teach_class_new.js, portal/templates/redesign/teach_new/class_new.html, portal/templates/redesign/teach_new/teacher_dismiss_students_new.html, portal/tests/pageObjects/portal/teach/class_page_new.py, portal/tests/pageObjects/portal/teach/dismiss_students_page_new.py, portal/tests/test_teacher_student_new.py, portal/urls.py, portal/views/teacher/teach_new.py
Functionality for releasing students from class added.
=> Redesign 28 - Edit class page: release students

portal/templates/redesign/terms_new.html
- Adds missing line break
- Updates font size of ordered list
- Adds correct double quotes characters
=> HTML/CSS fixes: Terms & Conditions page

portal/static/portal/sass/styles.scss, portal/templates/redesign/teach_new/materials_new.html
- Adds ZIP icons next to download buttons in materials page.
- Adds Key Stage tags next to materials sections in materials page.
=> HTML/CSS fixes: ZIP/Key Stage icons

portal/static/portal/sass/styles.scss, portal/templates/redesign/teach_new/dashboard.html, portal/templates/redesign/teach_new/teacher_move_all_classes_new.html, portal/tests/pageObjects/portal/teach/dashboard_page_new.py, portal/tests/pageObjects/portal/teach/move_classes_page_new.py, portal/tests/test_organisation_new.py, portal/urls.py, portal/views/organisation_new.py, portal/views/teacher/dashboard.py
- Non-admin teachers can now leave the organisation if they want.
- Upon leave request (or also when an administrator decides to remove a teacher from the school), if the teacher about to leave still has classes/students, the user has to choose who will take over the classes.
- and tests!
=> Redesign 32: Dashboard page for non admin teachers 

portal/static/portal/sass/styles.scss, portal/templates/redesign/home_new.html, portal/templates/redesign/play_new.html, portal/templates/redesign/teach_new.html, portal/templates/redesign/teach_new/dashboard.html, portal/templates/redesign/teach_new/materials_new.html, portal/templates/redesign/teach_new/onboarding_classes.html, portal/templates/redesign/teach_new/onboarding_print.html, portal/templates/redesign/teach_new/onboarding_school.html, portal/templates/redesign/teach_new/onboarding_students.html, portal/templates/redesign/terms_new.html
- The extra padding causing images to drop has been removed.
- The anchors & buttons in the dashboard tables don't look cluttered anymore.
- Responsiveness: After reaching a certain width (here, 1200px) the far-left and far-right margins are removed to avoid cluttered text and overlapping components.
=> HTML/CSS fixes: Padding, table buttons and responsiveness

portal/static/portal/sass/bootstrap_partials/_dropdown.scss, portal/static/portal/sass/bootstrap_partials/_glyphicons.scss, portal/static/portal/sass/bootstrap_partials/_grid.scss, portal/static/portal/sass/old_styles.scss
Adds the missing Bootstrap partials needed to make old pages have the correct header and footer.
=> Adds missing Bootstrap SASS

portal/forms/teach.py, portal/templates/portal/teach/dashboard.html, portal/templates/portal/teach/teacher_add_external_student.html, portal/templates/portal/teach/teacher_added_external_student.html, portal/templates/redesign/teach_new/teacher_add_external_student_new.html, portal/templates/redesign/teach_new/teacher_added_external_student_new.html, portal/tests/pageObjects/portal/play/join_school_or_club_page.py, portal/tests/pageObjects/portal/play/play_base_page.py, portal/tests/pageObjects/portal/teach/add_independent_student_to_class_page.py, portal/tests/pageObjects/portal/teach/add_independent_student_to_class_page_new.py, portal/tests/pageObjects/portal/teach/added_independent_student_to_class_page.py, portal/tests/pageObjects/portal/teach/added_independent_student_to_class_page_new.py, portal/tests/pageObjects/portal/teach/dashboard_page.py, portal/tests/test_independent_student.py, portal/urls.py, portal/views/teacher/dashboard.py
Teachers now have the ability to deny/allow independent students' requests to join their classes.
=> Redesign 31: Dashboard page - external requests

portal/forms/teach.py
=> Explanatory placeholder for add students form

portal/static/portal/sass/partials/_banners.scss, portal/static/portal/sass/partials/_buttons.scss, portal/templates/portal/teach/viewer.html
- Video has been made bigger and responsive.
- Download video button doesn't get cut in half when the screen becomes too small.
=> Updated resources banner layout

portal/views/home.py
=> Fix: No 2FA suggestion message on onboarding

.travis.yml, portal/tests/pageObjects/portal/teach/add_independent_student_to_class_page.py
'Cause of https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
=> Update Travis YAML file

portal/templates/portal/teach/dashboard.html, portal/templates/portal/teach/onboarding_complete.html
- Updated 'manage classes' button and added buttons on dashboard
- Links at end of onboarding
=> Updated dashboard buttons - again

portal/forms/teach.py
Teachers cannot register if their password isn't strong enough.
=> Register from: fix cleaning

portal/static/portal/sass/partials/_utils.scss
' - ' changed with symbol 2013
=> help and support FAQ moves to the left when clicked 

README.md
Hi,
The Contact Form on the main Code For Life website appears to have changed. I've corrected it in the ReadMe.
Cheers,
Clive
=> Corrected the Contact form URL

README.md
Stating where the contributing guideline file is.
=> Clearer contributing guidelines

portal/static/portal/js/sticky_subnav.js, portal/static/portal/sass/partials/_images-backgrounds.scss, portal/static/portal/sass/partials/_subnavs.scss, portal/templates/portal/teach/dashboard.html, portal/templates/portal/teach/onboarding_print.html, portal/tests/pageObjects/portal/teach/dashboard_page.py
- JS function for making bar sticky has been simplified.
- Deleted an unnecessary CSS class.
- Secondary button in sub nav bar now has appropriate behaviour.
- School name in 'New students created in class' page isn't hidden behind nav bar anymore.
=> Yellow warning sub nav bar: multiple fixes

.coveragerc, .travis.yml, ratelimit/backends/cache.py, ratelimit/decorators.py, reports/models.py, reports/urls.py
Coveralls ignores test files and egg files.
=> More accurate coverage

portal/static/portal/sass/old_styles.scss, portal/static/portal/sass/partials/_utils.scss, portal/templates/portal/play/student_edit_account.html
- Student password strength checker styles work.
- Success message box looks nice :+1:
=> Student pages: minor fixes

.scss-lint.yml, portal/static/portal/sass/modules/_all.scss, portal/static/portal/sass/modules/_colours.scss, portal/static/portal/sass/modules/_mixins.scss, portal/static/portal/sass/partials/_banners.scss, portal/static/portal/sass/partials/_base.scss, portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_footer.scss, portal/static/portal/sass/partials/_forms.scss, portal/static/portal/sass/partials/_header.scss, portal/static/portal/sass/partials/_images-backgrounds.scss, portal/static/portal/sass/partials/_onboarding.scss, portal/static/portal/sass/partials/_subnavs.scss, portal/static/portal/sass/partials/_tables.scss, portal/static/portal/sass/partials/_text.scss, portal/static/portal/sass/partials/_ui-dialog.scss, portal/static/portal/sass/partials/_utils.scss, portal/static/portal/sass/styles.scss, portal/templates/portal/login.html, portal/templates/portal/teach/dashboard.html, portal/tests/pageObjects/portal/teach/dashboard_page.py
Sass code follows rules of newly implemented BEM-style lint.
=> Re-enables SCSS lint

portal/tests/test_api.py, portal/urls.py, portal/views/api.py
(not including indep students)
=> Now can find out how many registered users per country - Fixes #629

CONTRIBUTING.md, README.md
I've added this in the contributing.md file because it seemed a lot more fitting - but should it still be in the main readme?
=> Updated contributing.md file

portal/static/portal/sass/partials/_text.scss
Redesign style has been brought back by nesting properly.
=> Home page: fix blockquotes

portal/forms/home.py, portal/helpers/regex.py
=> Incorrect regex fixed for multiline messages

portal/emailMessages.py, portal/urls.py, portal/views/email.py
The two methods were factorised and the references were updated.
=> Verify email and change email functions are now the same

portal/tests/test_independent_student.py, portal/tests/test_views.py, portal/tests/utils/student.py, portal/views/home.py
`is_safe_url` was not defined so when you try to redirect from a login form Django would raise an error
=> Fix login redirection bug

portal/static/portal/sass/partials/_utils.scss, portal/templates/portal/login.html, portal/templates/portal/register.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/689)
=> fixed responsiveness on login page

run.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/699)
=> Make run.bat equivalent to shell script

portal/views/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/701)
=> Phydeaux le chien admin userprofile

portal/templates/portal/teach/materials.html, portal/views/teacher/pdfs.py
The documents have been uploaded on google storage:
- ai:mmo user guide
- updated zip file for all ks3 resources
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/708)
=> Added AI:MMO user guide - fixes #703

portal/static/portal/sass/partials/_forms.scss, portal/templates/portal/register.html
Opening #711, meanwhile this is the current fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/712)
=> Minor fix to form--register before bigger refactoring. Solves #705

portal/templates/portal/terms.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/732)
=> New privacy policy

portal/templates/portal/terms.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/733)
=> implemented a few children-friendly changes suggested by privacy expert

portal/templates/portal/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/743)
=> fixes #742, C4L logo reappearing on firefox

portal/templates/portal/reset_password_email.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/753)
=> added image to reset_password_email.html to be tested

.gitignore
Hi,
My first pull request.
Regards,
Alexandre
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/764)
=> Add __pycache__ into .gitignore

portal/forms/organisation.py
Fixes autocomplete, however it is branched from master (unlike the last pull request) #735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/761)
=> Fixes autofill, is branched correctly

portal/forms/home.py, portal/tests/test_contact.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/765)
=> Can now enter special characters on contact form

portal/autoconfig.py, portal/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/769)
=> Rename players -> aimmo

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/770)
=> add a comment to setup test deps and run tests

setup.py
Upgraded version of Pillow to 3.3.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/773)
=> Upgraded vulnerable dependency in setup

setup.py
and two fa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/778)
=> Upgrade reversion

portal/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/782)
=> Fixes #691 - changed the search fields for failing admin pages

Pipfile, Pipfile.lock, README.md, run
Have also tested on dev, where it works fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/787)
=> Generated Pipfile, updated docs

portal/models.py, portal/tests/test_admin.py, portal/tests/utils/student.py, portal/views/home.py
Students are made preview users either when a teacher gains preview access or when a teacher with preview access adds a new class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/802)
=> Provide students from eligible school immediate preview access

portal/forms/teach.py, portal/templates/portal/teach/teacher_edit_student.html, portal/tests/pageObjects/portal/base_page.py, portal/tests/pageObjects/portal/play/account_page.py, portal/tests/test_independent_student.py, portal/tests/test_school_student.py, portal/tests/test_teacher_student.py, test_settings.py
- Fixed regex to accept dashes in name input form.
- Added tests to check success and failure or form depending on which characters are inputted.
- Moved one of the page objects defs in the test file to the base page so all page objects could inherit it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/810)
=> Student names with dashes are now accepted

portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_header.scss, portal/templates/portal/base.html, portal/templates/portal/teach/dashboard.html
- Added teacher buttons to menu box (Change my password + Update my details).
- Added bootstrap icons for each button.
- Updated styles such as font size, bottom border and hover action.
- Removed superfluous JavaScript and CSS and fixed minor column style issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/812)
=> Menu box update 1: teacher buttons

portal/templates/portal/base.html, portal/templates/portal/base_old.html
- As for #812, updated styles and positioning of menu box.
- Added button for the student to change their password.
- Removed unused JS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/820)
=> Menu box update 2: student buttons

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_task.md, .github/PULL_REQUEST_TEMPLATE/generic_pull_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request.md, .github/stale.yml
Adds git issue and PR templates as specified by [this](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) blog post first mentioned in the epic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/818)
=> Added templates for issues and a PR template

portal/views/home.py
The home page and the dashboard pages now have a banner informing users about the update in the terms and conditions, like so:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/857)
=> Banner for updated terms & conditions

portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/859)
=> Delete unused import

portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/867)
=> Removes updated terms banner

Pipfile.lock, setup.py, windows-requirements.txt
Upgraded the dependencies based on Github's alerts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/871)
=> Upgraded dependencies

portal/static/portal/sass/partials/_subnavs.scss
To be fixed on top
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/878)
=> Changed games subnav settings

portal/urls.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/882)
=> Deleted extra URL

portal/templates/portal/base.html, portal/templates/portal/play_rapid-router.html
From the rapid router page html to the base one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/914)
=> Moved Preview User Condition

portal/forms/auth_forms.py, portal/forms/play.py, portal/forms/registration.py, portal/forms/teach.py, portal/helpers/password.py, portal/migrations/0001_squashed_0041_new_news.py, portal/static/portal/js/passwordStrength.js, portal/tests/pageObjects/portal/signup_page.py, portal/tests/test_independent_student.py, portal/tests/test_school_student.py, portal/tests/test_teacher.py, portal/tests/utils/student.py, portal/tests/utils/teacher.py
Also changed automatically generated passwords to Password2 instead of Password1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/918)
=> Added password strength check + Tests

portal/templates/portal/teach/invite.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/923)
=> Added link to teacher dashboard on Cancel button

example_project/example_project/settings.py, example_project/example_project/urls.py, portal/tests/pageObjects/portal/materials_page.py, portal/tests/test_views.py, test_settings.py
We define the URLs within the example project to be consistent with production, which will also help to decouple the projects and later upgrade Django.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/932)
=> refactor: make URLs consistent with deployed project

portal/tests/test_api.py, portal/tests/utils/user.py, portal/urls.py, portal/views/api.py, setup.py
BREAKING CHANGE: Upgrading Django rest framework to 3.6.4
=> feat: Delete inactive users

portal/templates/portal/teach/materials.html, portal/views/teacher/pdfs.py, setup.py
Added KS3 Assessment documents to teaching packs and did a little reformatting to match the design suggested
=> feat: added ks3 assessment pdfs to materials page

portal/templates/portal/teach.html
Added Scottish curriculum file to the cloud and linked it on the website
Screenshot:
=> feat: added scottish curriculum link

portal/templates/portal/base.html, portal/templates/portal/teach/materials.html, portal/templates/portal/teach/teacher_resources.html
##Description
Adding Google Analytics events back in for when users download teaching resources.
=> fix: Sending GA event

portal/templates/portal/teach/materials.html
There was an syntax in one of the analytics events.
=> fix: GA syntax error

.codecov.yml, .travis.yml, README.md
Transitioning from coveralls to codecov coverage, as it's used in the AI:MMO project.
=> feat: integrating codecov

portal/templates/portal/base.html
=> fix: align newsletter form and social media icons in footer

portal/autoconfig.py, portal/templates/portal/login.html, portal/templates/portal/play/student_details.html, portal/templates/portal/play/student_edit_account.html, portal/templates/portal/play/student_join_organisation.html, setup.py
Upgrading to django-pipeline 1.6.14 and adding Jinja2 to setup.py so we can merge in RR PR.
=> fix: Upgrade to django-pipeline 1.6.14

Pipfile.lock, portal/autoconfig.py, portal/tests/base_test.py, portal/tests/selenium_test_case.py, portal/tests/test_independent_student.py, setup.py, test_settings.py
also remove support form django-pipeline 1.5.4
=> fix: missing css bug

portal/views/home.py
=> fix: Escape message content

portal/static/portal/sass/partials/_banners.scss, portal/static/portal/sass/partials/_grids.scss, portal/static/portal/sass/partials/_images.scss, portal/static/portal/sass/partials/_text.scss, portal/static/portal/sass/partials/_videos.scss, portal/templates/portal/partials/benefits.html, portal/templates/portal/play_aimmo.html, portal/tests/snapshots/snap_test_partials.py, portal/views/home.py
UI fixes to new Kurono play page and benefits partials caught in QA. Redirect to old Kurono (preview) page before launch.
=> fix: Kurono landing qa fixes

docs/online_status_middleware.md, portal/views/home.py
Added a cache control header set to private on the home view. Removed online status doc.
=> feat: change cache control to private

portal/templates/portal/aimmo_home.html, portal/templates/portal/teach/materials.html, portal/tests/pageObjects/portal/materials_page.py, portal/tests/test_materials.py, portal/views/aimmo/home.py, portal/views/teacher/pdfs.py, portal/views/teacher/teach.py, portal/views/teacher/teacher_materials.py
This PR links the portal to the new Kurono student challenges designed by @lauracumming.
It also fixes the material viewer's issues:
- The link to the other Kurono challenge is called Kurono instead of AIMMO
- The PDF names are now Kurono instead of AIMMO
- The capitalisation logic had to be tweaked so as to not capitalise 'KUROno'
This also fixes the 14-18 text to 13-18 in the Kurono description.
=> feat: Upload new Kurono student challenges

Pipfile.lock, setup.py
=> fix: Remove django-forms-bootstrap from portal

Pipfile.lock, portal/autoconfig.py, setup.py
Removed `django-jquery` dependency.
=> fix: remove django jquery

Pipfile.lock, setup.py
Upgraded dependency `django-two-factor-auth` to version 1.9.1
=> feat: upgraded django-two-factor-auth to 1.9.1

Pipfile.lock, setup.py
Upgraded `reportlab` dependency to version 3.5.32.
=> feat: upgraded reportlab to 3.5.32

portal/templates/portal/base.html, portal/templates/portal/base_old.html, portal/templates/portal/login.html, portal/templates/portal/play.html, portal/templates/portal/play_aimmo.html, portal/templates/portal/register.html, portal/templates/portal/teach/materials.html, portal/tests/base_test.py, portal/tests/pageObjects/portal/login_page.py, portal/tests/pageObjects/portal/signup_page.py, portal/tests/selenium_test_case.py, portal/tests/test_admin.py, portal/tests/test_views.py, portal/views/home.py
so we can test the correct logic
=> fix: Fix captcha login error

Pipfile.lock, setup.py
Uninstalled `urllib3`. It's installed by the dependency `responses`.
=> fix: uninstalled urllib3

.travis.yml, Pipfile, Pipfile.lock, example_project/example_project/settings.py, portal/__init__.py, portal/forms/admin_login.py, portal/migrations/0001_squashed_0041_new_news.py, portal/templates/portal/help-and-support.html, portal/templates/registration/login.html, portal/tests/pageObjects/portal/forbidden_page.py, portal/tests/pageObjects/portal/help_and_support_page.py, portal/tests/test_admin.py, portal/tests/test_contact.py, portal/tests/test_views.py, portal/tests/utils/email.py, portal/views/admin.py, portal/views/home.py, setup.py, test_settings.py
This PR removes a bytestring to make portal fully compatible with Python 3.
=> fix: Remove bytestring

portal/strings/play.py, portal/strings/play_aimmo.py, portal/templates/portal/partials/headline.html, portal/templates/portal/play_aimmo.html
Updated copy as described in the copywriting document.
=> fix: updated copy

.travis.yml, portal/views/aimmo/home.py
This PR makes sure the game creation is done using the same logic as the one in the aimmo project.
This fixes the refresh bug as the duplicated logic in portal was missing the creation of the avatar.
=> fix: Use same logic as aimmo for game creation

portal/templates/portal/aimmo_home.html, portal/urls.py, portal/views/aimmo/home.py, portal/views/teacher/pdfs.py
This PR adds the new worksheet PDFs for Kurono to the website.
This includes:
- The 2 student challenges
- The 2 teacher guides
- The user guide
- The Kurono API guide (which replaces the Code Cheat Sheet)
**NB**: The UX for this will be reviewed as part of the whole Kurono dashboard review by @lauracumming in a separate PR.
=> feat: Upload new Kurono worksheets

portal/views/home.py
Signed-off-by: Niket <niket.shah1@ocado.com>
=> fix: Unimported module caused 2FA cache not to clear

.travis.yml, portal/app_settings.py, portal/autoconfig.py, portal/context_processors.py, portal/templates/portal/base.html, portal/templates/portal/base_old.html, portal/templates/portal/tag_manager/tag_manager_body.html, portal/templates/portal/tag_manager/tag_manager_head.html, portal/tests/test_views.py, portal/views/home.py
In this PR I have also made the home learning banner hidden so we can deploy now and release it when we are ready via a tag
=> feat: Integrate Google Tag manager

portal/static/portal/sass/partials/_grids.scss, portal/strings/home_learning.py, portal/templates/portal/home_learning.html, portal/tests/test_views.py, portal/views/home.py
=> fix: Update response landing page

portal/templates/500.html, portal/templates/portal/about.html, portal/templates/portal/base.html, portal/templates/portal/base_old.html, portal/tests/pageObjects/portal/teacher_login_page.py, portal/tests/test_views.py, portal/views/login/teacher.py
Also updates Ocado logos link.
=> fix: Fix teacher login recaptcha issue

portal/static/portal/sass/partials/_grids.scss, portal/templates/portal/home_learning.html, portal/templates/portal/partials/hero_card.html, portal/templatetags/banner_tags.py, portal/templatetags/benefits_tags.py, portal/templatetags/game_banner_tags.py, portal/templatetags/headline_tags.py, portal/templatetags/hero_card_tags.py, portal/tests/snapshots/snap_test_partials.py, portal/tests/test_partials.py
Test above of what it would look like
=> feat: Create hero card partial

portal/views/aimmo/home.py
Signed-off-by: Niket <niket.shah1@ocado.com>
=> fix: aimmo dashboard page for students

cfl_common/MANIFEST.in
Signed-off-by: Niket <niket.shah1@ocado.com>
=> fix: Add MANIFEST.in to common package to include fixture files

portal/templates/portal/viewer.html
Hides the banner which links to teacher materials from students.
=> fix: hide KS banners from students

portal/templates/portal/teach/kurono_teaching_packs.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1336)
=> fix: Update Kurono zip link

.github/workflows/ci.yml, portal/forms/add_game.py, portal/game_creator.py, portal/static/portal/js/join_create_game_toggle.js, portal/static/portal/sass/partials/_subnavs.scss, portal/templates/portal/teach/kurono_teaching_packs.html, portal/templates/portal/teach/teacher_aimmo_dashboard.html, portal/tests/forms/test_add_game.py, portal/tests/test_teacher.py, portal/views/aimmo/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1339)
=> feat: Add game dropdown

.github/workflows/ci.yml, Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1341)
=> fix: cleanup add game dropdown

portal/templates/portal/teach/teacher_aimmo_dashboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1344)
=> fix: Update resources section of Kurono dashboard

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1345)
=> fix: static version for python-semantic-release

portal/templates/portal/base.html, portal/templates/portal/base_old.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1348)
=> fix: change recaptcha source to use their domain

Pipfile.lock, portal/templates/portal/teach/kurono_teaching_packs.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1346)
=> fix: Add solutions file to Kurono packs

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1352)
=> fix: rr migrations tests

portal/templates/500.html, portal/templates/portal/base.html, portal/templates/portal/base_old.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1361)
=> fix: update copyright to use current year

portal/strings/play_aimmo.py, portal/templates/portal/play_aimmo.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1362)
=> fix: Update copy of Kurono landing page

portal/templates/portal/viewer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1363)
=> fix: Update PDF viewer nav buttons

cfl_common/common/app_settings.py, cfl_common/common/helpers/emails.py, portal/tests/test_emails.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1365)
=> feat: Capture consent data on newsletter signup

portal/templates/registration/login.html, portal/views/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1373)
=> fix: Improve admin login form

portal/autoconfig.py, portal/templates/portal/base.html, portal/templates/portal/base_old.html
and add RECAPTCHA_DOMAIN setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1383)
=> fix: remove recaptcha from header

portal/static/portal/js/aimmoGame.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1384)
=> fix: Improve popup text generation

portal/templates/portal/teach/kurono_teaching_packs.html, portal/templates/portal/teach/teacher_aimmo_dashboard.html, portal/views/teacher/pdfs.py
Links tested on portal.
Includes some indentation updates by black.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1404)
=> feat: add and update kurono files for w3 etc

cfl_common/common/fixtures/unlock_worksheet3.json, cfl_common/common/migrations/0008_unlock_worksheet_3.py, cfl_common/common/tests/test_migration_worksheets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1405)
=> feat: enable worksheet 3

portal/templates/portal/teach/kurono_teaching_packs.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1406)
=> fix: update links to new kurono_teacher_solutions

.github/workflows/ci.yml, package.json, portal/tests/test_materials.py, portal/views/teacher/pdfs.py, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1408)
=> fix: fix pdf url, add and adjust tests

portal/templates/portal/base.html, portal/templates/portal/base_old.html, portal/templatetags/app_tags.py
Ignore the old branch analytics_onprod. This time I made sure there's no auto re-indentation as I spent way too much time trying to resolve the error caused by auto-indentation and couldn't resolve it :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1411)
=> feat: call google analytics only on production

portal/templates/portal/base.html, portal/templates/portal/privacy_policy.html, portal/urls.py, portal/views/privacy_policy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1410)
=> feat: Update privacy policy

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml, Pipfile, Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1415)
=> feat: update python version to 3.7

portal/templates/portal/privacy_policy.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1421)
=> fix: Add bullet points to privacy policy table

portal/templates/portal/privacy_policy.html, portal/views/privacy_policy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1422)
=> fix: update-privacy-policy

portal/views/teacher/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1426)
=> fix: require post

portal/tests/test_2FA.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1425)
=> fix: add tests for 2FA

portal/tests/test_emails.py, portal/views/dotmailer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1427)
=> fix: Handle if user not registered

portal/tests/test_emails.py, portal/views/dotmailer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1428)
=> fix: Fix try except in Dotmailer form view

portal/templates/portal/base_old.html, portal/templates/portal/mouseflow.html, portal/templates/portal/teach/class.html
- add integrity hash to mouseflow
- remove links to inexistent jquery-ui file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1431)
=> fix: add integrity hash and fix js links

portal/templates/portal/mouseflow.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1434)
=> fix: crossOrigin is case sensitive via js

portal/forms/play.py, portal/forms/registration.py, portal/forms/teach.py, portal/templates/portal/login/independent_student.html, portal/templates/portal/login/student.html, portal/templates/portal/login/teacher.html, portal/templates/portal/register.html, portal/templates/portal/reset_password_student.html, portal/templates/portal/reset_password_teach.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1435)
=> fix: Remove autocomplete

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml
Tested the following on push:
```
- name: Test trigger dev deployment
uses: actions/github-script@v4
with:
github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
script: |
github.actions.createWorkflowDispatch({
owner: 'ocadotechnology',
repo: 'codeforlife-deploy-appengine',
workflow_id: 'deploy_dev.yml',
ref: 'debug-ratelimit',
});
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1438)
=> fix: trigger staging deployment

cfl_common/common/tests/utils/email.py, cfl_common/common/tests/utils/student.py, cfl_common/common/tests/utils/teacher.py, portal/templates/portal/email_verification_needed.html, portal/templates/portal/play/student_details.html, portal/templates/portal/teach/dashboard.html, portal/templatetags/app_tags.py, portal/tests/pageObjects/portal/play/dashboard_page.py, portal/tests/pageObjects/portal/teach/dashboard_page.py, portal/tests/test_independent_student.py, portal/tests/test_teacher.py, portal/tests/utils/messages.py, portal/urls.py, portal/views/email.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1442)
=> fix: Add verification banner

portal/forms/teach.py, portal/helpers/decorators.py, portal/helpers/ratelimit.py, portal/tests/test_ratelimit.py, portal/urls.py, portal/views/login/independent_student.py, portal/views/login/teacher.py, portal/views/registration.py, portal/views/student/edit_account_details.py, portal/views/teacher/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1443)
=> fix: ratelimit

.gitbook.yaml, README.md, SUMMARY.md
Revert the previous gitbook updates. Better to not use gitbook sync feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1445)
=> docs: revert gitbook changes

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1454)
=> fix: update lock file for django2.2.21

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1458)
=> fix: Update lockfile - Django 2.2.22

cfl_common/common/email_messages.py, cfl_common/common/helpers/emails.py, portal/tests/test_independent_student.py, portal/tests/test_teacher.py, portal/views/email.py, portal/views/student/edit_account_details.py, portal/views/teacher/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1464)
=> fix: Check for existing user on email change + change username

install-win.bat, portal/templates/portal/teach/base_registering.html
Also sneaking in a removal of a win file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1468)
=> fix: add kurono link on onboarding phase

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1469)
=> docs: Update ci to ignore md files

Pipfile.lock, portal/forms/play.py, portal/forms/teach.py, portal/tests/cypress/support/commands.ts, portal/tests/test_2FA.py, portal/tests/test_aimmo_dashboards.py, portal/tests/test_captcha_forms.py, portal/tests/test_materials.py, portal/tests/test_ratelimit.py, portal/tests/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1494)
=> fix: Remove ReCaptcha from certain forms

portal/tests/pageObjects/portal/home_page.py
Adds a "teacher_logout" function to the HomePage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1497)
=> feat: add function teacher_logout to HomePage

portal/static/portal/sass/modules/_homepage_constants.scss, portal/static/portal/sass/partials/_header.scss, portal/static/portal/sass/partials/_images.scss, portal/static/portal/sass/partials/_subnavs.scss, portal/static/portal/sass/styles.scss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1516)
=> fix: rebranding logo spacing

portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_forms.scss, portal/templates/portal/home_learning.html, portal/templates/portal/partials/benefits.html, portal/templates/portal/play/student_details.html, portal/templates/portal/teach/class.html, portal/templates/portal/teach/dashboard.html, portal/templates/portal/teach/onboarding_complete.html, portal/templates/portal/teach/onboarding_school.html, portal/templates/portal/teach/teacher_add_external_student.html, portal/templates/portal/teach/teacher_aimmo_dashboard.html, portal/templates/portal/teach/teacher_dismiss_students.html, portal/templates/portal/teach/teacher_edit_class.html, portal/templates/portal/teach/teacher_move_all_classes.html, portal/templates/portal/teach/teacher_move_class.html, portal/templates/portal/viewer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1517)
=> fix: button updates etc

portal/forms/play.py, portal/forms/teach.py, portal/static/portal/sass/partials/_banners.scss, portal/static/portal/sass/partials/_grids.scss, portal/strings/play_rapid_router.py, portal/templates/portal/home_learning.html, portal/templates/portal/partials/benefits.html, portal/templates/portal/partials/card_list.html, portal/templates/portal/partials/character_list.html, portal/templates/portal/partials/hero_card.html, portal/templates/portal/play/student_aimmo_dashboard.html, portal/templates/portal/play/student_details.html, portal/templates/portal/teach/kurono_teaching_packs.html, portal/templatetags/benefits_tags.py, portal/tests/snapshots/snap_test_partials.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1521)
=> fix: rebranding adjustments

portal/templates/portal/base.html, portal/templates/portal/play.html, portal/templates/portal/play_aimmo.html, portal/templates/portal/teach/kurono_teaching_packs.html, portal/templates/portal/teach/materials.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1522)
=> fix: remove page caches

portal/templates/portal/privacy_policy.html, portal/views/privacy_policy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1526)
=> fix: Privacy Policy update

portal/static/portal/sass/partials/_buttons.scss, portal/static/portal/sass/partials/_header.scss, portal/static/portal/sass/partials/_subnavs.scss, portal/templates/portal/dotmailer_consent_form.html, portal/templates/portal/partials/aimmo_games_table.html, portal/templates/portal/teach/class.html, portal/templates/portal/teach/dashboard.html, portal/templates/portal/teach/onboarding_classes.html, portal/templates/portal/teach/onboarding_school.html, portal/templates/portal/teach/teacher_move_all_classes.html, portal/templates/portal/teach/teacher_student_reset.html
There are also a few icons for the rebranding phase 2. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1536)
=> fix: button and table updates (rebranding 1 amends)

portal/forms/organisation.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1541)
=> feat: remove flags

portal/static/portal/sass/partials/_banners.scss, portal/templates/portal/teach/teacher_aimmo_dashboard.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1545)
=> fix: reposition banner image

Pipfile.lock, cfl_common/common/helpers/generators.py, portal/forms/play.py, portal/forms/registration.py, portal/forms/teach.py, portal/helpers/password.py, portal/tests/test_school_student.py, portal/tests/test_teacher_student.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1550)
=> feat: class code and student password format

example_project/settings.py, portal/autoconfig.py, portal/tests/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1557)
=> fix: update autoconfig settings for random URL

portal/static/portal/sass/partials/_buttons.scss, portal/templates/portal/teach/onboarding_print.html, portal/tests/test_views.py, portal/urls.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1561)
=> feat: add csv download

cfl_common/common/tests/utils/student.py, portal/tests/test_teacher_student.py, portal/tests/test_views.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1600)
=> fix: fixes for student deletion

portal/templates/portal/partials/header.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1605)
=> fix: student dashboard logo link

portal/templates/portal/about.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1620)
=> fix: about us image

portal/csp_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1641)
=> fix: Add GCP bucket to CSP list

portal/csp_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1646)
=> fix: Add GA connection to CSP config

portal/static/portal/sass/partials/_subnavs.scss, portal/templates/portal/partials/header.html, portal/tests/pageObjects/portal/base_page.py, portal/tests/pageObjects/portal/play/dashboard_page.py, portal/views/login/independent_student.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1649)
=> feat: navbar updates for indep and teacher

portal/tests/test_views.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1663)
=> feat: add password to csv

portal/tests/test_views.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1670)
=> fix: add class link to csv

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1674)
=> build: Update lockfile

portal/templates/portal/play.html, portal/tests/pageObjects/portal/base_page.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1687)
=> fix: Fix Play page headers

portal/tests/pageObjects/portal/base_page.py, portal/tests/pageObjects/portal/teach/class_page.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1688)
=> fix: add sleep to tests

portal/static/portal/sass/modules/_levels.scss, portal/templates/portal/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1691)
=> fix: keep dropdown open while scrolling

portal/templatetags/app_tags.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1693)
=> fix: independent student check

portal/static/portal/sass/partials/_subnavs.scss, portal/templatetags/app_tags.py
Changes to be used in RR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1694)
=> feat: add subnav styles and fix login check

portal/static/portal/sass/partials/_forms.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1701)
=> fix: align filter and search on scoreboard

portal/templates/portal/teach/teacher_dismiss_students.html, portal/tests/test_views.py, portal/views/login/independent_student.py, portal/views/login/student.py, portal/views/login/teacher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1711)
=> fix: allow any login view after logging in

portal/static/portal/sass/partials/_banners.scss, portal/templates/portal/play.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1712)
=> fix: Rename RR banner class

portal/templates/portal/partials/header.html, portal/templates/portal/teach/dashboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1719)
=> fix: additional account details updates

cfl_common/common/templates/common/onetrust_cookies_consent_notice.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1726)
=> fix: update cookies test script

Pipfile.lock, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1727)
=> build(deps): bump Django from 2.2.25 to 2.2.26

portal/templates/portal/partials/aimmo_games_table.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1729)
=> fix: Reference button correctly in games table

cfl_common/MANIFEST.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1730)
=> fix: add common static to manifest

cfl_common/common/templates/common/onetrust_cookies_consent_notice.html
Safe to deploy as it only affects non-prod environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1752)
=> fix: update test cookies consent script

portal/views/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1757)
=> fix: indy teacher cleanup in batches

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1761)
=> fix: Update pyyaml to 5.4.1

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1762)
=> build: Update lockfile for Django 2.2.27

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1764)
=> fix: trim ci flow

portal/templates/portal/teach/teacher_dismiss_students.html, portal/tests/pageObjects/portal/teach/class_page.py, portal/tests/pageObjects/portal/teach/dismiss_students_page.py, portal/tests/test_teacher_student.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1766)
=> fix: no duplicate email on student release

portal/tests/test_location.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1775)
=> fix: duplicate postcode test

portal/tests/test_api.py, portal/tests/test_invite_teacher.py, portal/tests/test_location.py, portal/tests/test_newsletter_footer.py, portal/tests/test_security.py, portal/tests/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1777)
=> fix: remove assertEqual/s

portal/static/portal/sass/partials/_header.scss, portal/views/teacher/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1781)
=> fix: Remove padding in dropdown options

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1789)
=> fix: Upgrade semantic-release version

portal/tests/test_api.py, portal/views/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1793)
=> fix: the last indy/teacher clean up

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1794)
=> fix: continue publishing after pypi error

portal/views/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1795)
=> fix: indy cleanup - priorities last login

portal/static/portal/sass/partials/_forms.scss, portal/static/portal/sass/partials/_tables.scss, portal/templates/portal/login/independent_student.html, portal/templates/portal/login/student.html, portal/templates/portal/login/teacher.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1797)
=> fix: Login forms inconsistencies

portal/templates/portal/reset_password_email_sent.html, portal/templates/portal/teach/teacher_dismiss_students.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1799)
=> Usernamefixes

.github/workflows/ci.yml, Pipfile, Pipfile.lock, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1800)
=> fix: cleanup ci and update pipfile

portal/templates/portal/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1815)
=> fix: remove missing script

portal/views/registration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1818)
=> fix: fix sending email on account deletion

cfl_common/common/email_messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1819)
=> fix: deletion email minor updates

portal/tests/test_views.py, portal/views/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1822)
=> fix: delete class and students on account deletion

.github/workflows/semantic-pull-request-check.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1839)
=> build: Add semantic PR check as action

.github/workflows/ci.yml, Pipfile, portal/autoconfig.py, portal/tests/test_react_test_space.py, portal/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1858)
=> fix: remove CI steps that broke deployment

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml, portal/autoconfig.py, portal/tests/test_react_test_space.py, portal/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1859)
=> fix: edit the deployment for react test space

portal_frontend/src/Components/Footer/FooterMenu.tsx, portal_frontend/src/Components/Navbar/Dashboard.tsx, portal_frontend/src/Components/Navbar/Games.tsx, portal_frontend/src/Components/Navbar/LearningResources.tsx, portal_frontend/src/Components/Navbar/NavbarStyle.tsx, portal_frontend/src/Components/Navbar/UserLogInButton.tsx
Mui is throwing some errors on staging, this was one of the fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1870)
=> fix: updated mui compatible colours

portal/autoconfig.py, portal/tests/test_newsletter_footer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1877)
=> fix: Set referrer policy to preferred value

cfl_common/common/tests/utils/student.py, portal/forms/play.py, portal/forms/registration.py, portal/templates/portal/register.html, portal/tests/pageObjects/portal/signup_page.py, portal/tests/test_independent_student.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1882)
=> fix: Update registration page

cfl_common/common/email_messages.py, portal/forms/registration.py, portal/tests/test_invite_teacher.py, portal/views/teacher/dashboard.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1892)
=> fix: email below text

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1902)
=> fix: try the latest python-semantic-release version

portal/csp_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1906)
=> fix: Add common static to object src in CSP

cfl_common/common/permissions.py, portal/templates/portal/teach/dashboard.html, portal/tests/test_admin.py, portal/tests/test_independent_student.py, portal/tests/test_teacher.py, portal/tests/test_teacher_student.py, portal/views/teacher/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1914)
=> feat: Show all external requests in school to admins

deploy/middleware/session_timeout.py, portal/app_settings.py, portal/static/portal/js/common.js, portal/static/portal/sass/partials/_popup.scss, portal/templates/portal/base.html, portal/templates/portal/partials/session_popup.html, portal/tests/test_middleware.py, portal/urls.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1918)
=> feat: Add session timeout warning popup

example_project/manage.py, example_project/test_settings.py, portal/tests/test_views.py, pytest.ini, run, run_testserver
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1928)
=> fix: collectstatic command

portal/static/portal/sass/partials/_forms.scss, portal/templates/portal/register.html, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1934)
=> fix: Update text in registration forms

portal/templates/portal/coding_club.html, portal/views/home.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1936)
=> fix: python download texts and update buttons with zip downloads

portal/tests/test_middleware.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1941)
=> fix: Make kurono maintenance banner show depending on flag

portal/templates/portal/privacy_policy.html, portal/views/legal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1943)
=> fix: Update contact email in Privacy Policy

Pipfile.lock, cfl_common/common/migrations/0030_add_maintenance_banner.py, portal/admin.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1951)
=> fix: Add maintenance banner

portal/static/portal/sass/partials/_buttons.scss, portal/templates/portal/partials/aimmo_games_table.html, portal/templates/portal/teach/teacher_aimmo_dashboard.html, portal/tests/test_aimmo_dashboards.py, portal/views/aimmo/dashboard.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1952)
=> feat: admin aimmo power portal feature

portal/static/portal/js/aimmoGame.js, portal/tests/test_class.py, portal/views/teacher/teach.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1953)
=> fix: added a bug fix for class deletion and game still being up

portal/helpers/password.py, portal/tests/pageObjects/portal/password_reset_form_page.py, portal/tests/test_teacher.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1955)
=> feat: reset password must be different to the current password 

Pipfile, Pipfile.lock, portal/tests/base_test.py, portal/tests/snapshots/snap_test_partials.py, portal/tests/test_invite_teacher.py, portal/tests/test_teacher.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1958)
=> fix: fix most common flaky tests #1

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1963)
=> build: Update lockfile for Django 3.2.16

portal/templates/portal/privacy_policy.html, portal/views/legal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1974)
=> fix: Revert privacy email and fix broken link

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1982)
=> build: Upgrade certifi

portal/templates/portal/getinvolved.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1986)
=> fix: fixed the typo

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml, .github/workflows/semantic-pull-request-check.yml, .github/workflows/snyk.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1987)
=> build: Update Github actions

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1988)
=> build: Update github script

portal/templates/portal/getinvolved.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1993)
=> fix: made the the page open in the same window

portal/templates/portal/privacy_policy.html, portal/views/legal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1997)
=> fix: Updates to privacy policy

Pipfile.lock, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2015)
=> fix: Update old divs

portal/templates/portal/privacy_notice.html, portal/views/legal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2016)
=> fix: Update PN section on personal data

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2028)
=> fix: Patch update for more-itertools

Pipfile, Pipfile.lock, portal/admin.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2087)
=> fix: Remove old arg from School admin

portal/templates/portal/base.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2089)
=> fix: script loading

portal/static/portal/js/riveted.min.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2096)
=> fix: Bring back Riveted

Pipfile.lock, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2097)
=> build: Update reportlab and requests

cfl_common/common/email_messages.py, cfl_common/common/helpers/emails.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2101)
=> fix: 1454 shorten url in aws emails

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml, .github/workflows/snyk.yaml, Dockerfile, Pipfile, Pipfile.lock, setup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2104)
=> feat: Upgrade Python to 3.8

Pipfile.lock, portal/static/portal/js/passwordStrength.js, portal/tests/base_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2117)
=> fix: Fix logic of frontend password strength check

portal/static/portal/js/passwordStrength.js, portal/templates/portal/register.html, portal/templates/portal/reset_password_confirm.html, portal/views/registration.py
And fix small bug on password reset email check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2149)
=> fix: Get correct fields for password strength check

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2150)
=> fix: Fix semantic release to < 8

.github/workflows/ci.yml, portal/tests/conftest.py, portal/tests/test_class.py, portal/tests/test_teacher.py, portal/views/aimmo/dashboard.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2153)
=> fix: Update how Kurono games are created

cfl_common/common/migrations/0041_populate_gb_counties.py, cfl_common/common/models.py, cfl_common/common/tests/test_models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2161)
=> fix: Handle empty postcode edge case

portal/tests/test_views.py, portal/views/cron/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2166)
=> fix: Shorten verify email link

portal/helpers/ratelimit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2178)
=> fix: Disable ratelimit when value is empty

cfl_common/common/migrations/0048_unique_school_names.py, cfl_common/common/tests/test_0048_unique_school_names.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2232)
=> fix: migration common_0048

cfl_common/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2235)
=> fix: Upgrade Django to 3.2.23 (CI/CD measuring)

cfl_common/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2237)
=> build: Downgrade Django (CI/CD measuring)

cfl_common/setup.py
https://github.com/pypa/gh-action-pypi-publish/issues/162
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2246)
=> fix: Try adding long desc to common setup

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2247)
=> fix: git user to cfl-bot

portal/templates/portal/partials/footer.html, portal/templates/portal/partials/header.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2257)
=> feat: Add link to 2023 Impact Report

Pipfile.lock, portal/tests/test_views.py, portal/views/student/play.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2265)
=> fix: Fix scoring data in student dashboard

Pipfile.lock, portal/templates/portal/email_verification_needed.html, portal/templates/portal/reset_password_email_sent.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2268)
=> fix: Make email spam warning more prominent

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2278)
=> ci: test discovery

portal/templates/portal/email_verification_needed.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2283)
=> fix: Update from email address in Gmail button filter

portal/templates/portal/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2287)
=> fix: Move jQuery load earlier

example_project/portal_test_settings.py, example_project/settings.py, portal/tests/test_emails.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2288)
=> build: Enable atomic transactions

cfl_common/common/migrations/0049_anonymise_orphan_users.py, cfl_common/common/migrations/0050_anonymise_orphan_schools.py, cfl_common/common/migrations/0051_verify_returning_users.py, cfl_common/common/models.py, cfl_common/common/tests/test_migration_anonymise_orphan_schools.py, cfl_common/common/tests/test_migration_anonymise_orphan_users.py, cfl_common/common/tests/test_migration_unique_school_names.py, cfl_common/common/tests/test_migration_verify_returning_users.py, portal/tests/test_api.py, portal/views/login/student.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2290)
=> feat: Clean illogical data

portal/tests/test_emails.py, portal/urls.py, portal/views/email.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2307)
=> fix: Remove legacy weekly stats email

portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2347)
=> fix: Fix permissions check for moving students

portal/templates/portal/partials/header.html
https://www.searchpilot.com/resources/case-studies/testing-data-nosnippet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2349)
=> fix: Add data-nosnippet to login spans

portal/tests/test_views.py, portal/views/cron/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2357)
=> fix: Add personalisation values to reminder emails

portal/urls.py, portal/views/cron/user.py, portal/views/home.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2374)
=> fix: Disable DB gateways

portal/templates/portal/teach/teacher_edit_class.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2393)
=> fix: worksheet counter

portal/templates/portal/partials/footer.html, portal/templates/portal/partials/header.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2397)
=> feat: Impact Report 2024

portal/forms/teach.py, portal/templates/portal/teach/dashboard.html, portal/tests/test_class.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2406)
=> fix: Class name field characters

Pipfile.lock, portal/views/teacher/dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2410)
=> feat: Share levels with teachers and require moderation on join

portal/urls.py, portal/views/google_analytics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2414)
=> fix: ga collect

portal/forms/teach.py, portal/templates/portal/teach/teacher_edit_class.html, portal/tests/test_class.py, portal/views/teacher/teach.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2416)
=> fix: episode indexing

cfl_common/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2417)
=> fix: django v4.2.20

cfl_common/Pipfile, cfl_common/Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2427)
=> feat: django 5.2

cfl_common/Pipfile, cfl_common/Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2428)
=> fix: django 5.1

example_project/portal_test_settings.py, example_project/settings.py, portal/templates/403.html, portal/templates/500.html, portal/templates/maintenance.html, portal/templates/portal/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2438)
=> fix: sass compiler

cfl_common/Pipfile, cfl_common/Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/2443)
=> fix: django 5.9.10
